[
    {
        "id": "",
        "label": "HYDROGEN OSC INTERFACE",
        "widgets": [
            {
                "type": "toggle",
                "top": 0,
                "left": 30,
                "id": "MUTE/UNMUTE",
                "linkId": "",
                "label": "auto",
                "width": 110,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "value": "",
                "precision": 2,
                "address": "/Hydrogen/MUTE_TOGGLE",
                "preArgs": [],
                "target": []
            },
            {
                "type": "fader",
                "top": 60,
                "left": 30,
                "id": "Master",
                "linkId": "",
                "label": "auto",
                "unit": "",
                "width": "auto",
                "height": 600,
                "alignRight": false,
                "horizontal": false,
                "noPip": false,
                "compact": false,
                "color": "auto",
                "css": "",
                "snap": false,
                "spring": false,
                "range": {
                    "min": 0,
                    "max": 1.5
                },
                "origin": "auto",
                "value": "",
                "logScale": false,
                "precision": 1,
                "meter": false,
                "address": "/Hydrogen/MASTER_VOLUME_ABSOLUTE",
                "touchAddress": "",
                "meterAddress": "",
                "preArgs": [],
                "target": []
            },
            {
                "type": "multifader",
                "top": 60,
                "left": 130,
                "id": "Instr Volume",
                "strips": 8,
                "start": 1,
                "label": "auto",
                "unit": "",
                "width": 480,
                "height": 600,
                "alignRight": false,
                "horizontal": false,
                "noPip": true,
                "compact": false,
                "color": "auto",
                "css": "",
                "traversing": true,
                "snap": true,
                "range": {
                    "min": 0,
                    "max": 1.5
                },
                "value": "",
                "origin": "auto",
                "logScale": false,
                "precision": 2,
                "meter": false,
                "address": "/Hydrogen/STRIP_VOLUME_ABSOLUTE",
                "preArgs": [],
                "split": true,
                "target": []
            },
            {
                "type": "push",
                "top": 0,
                "left": 140,
                "id": "MUTE",
                "linkId": "",
                "label": "auto",
                "width": 80,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/MUTE",
                "preArgs": [],
                "target": []
            },
            {
                "type": "push",
                "top": 0,
                "left": 300,
                "id": "PLAY",
                "label": "auto",
                "width": "auto",
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/PLAY",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "toggle",
                "top": 0,
                "left": 500,
                "id": "PLAY/STOP",
                "label": "auto",
                "width": 110,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "value": "",
                "precision": 2,
                "address": "/Hydrogen/PLAY_STOP_TOGGLE",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "push",
                "top": 0,
                "left": 400,
                "id": "STOP",
                "label": "auto",
                "width": "auto",
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/STOP",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "push",
                "top": 70,
                "left": 700,
                "id": "RECORD_READY",
                "label": "auto",
                "width": 160,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/RECORD_READY",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "push",
                "top": 70,
                "left": 860,
                "id": "RECORD_EXIT",
                "label": "auto",
                "width": 160,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/RECORD_EXIT",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "push",
                "top": 130,
                "left": 700,
                "id": "RECORD_STROBE",
                "label": "auto",
                "width": 160,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/RECORD_READY",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "toggle",
                "top": 130,
                "left": 860,
                "id": "RECORD_STROBE",
                "label": "auto",
                "width": 160,
                "height": 60,
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "value": "",
                "precision": 2,
                "address": "/Hydrogen/RECORD_STROBE_TOGGLE",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "push",
                "top": 0,
                "left": 220,
                "id": "UNMUTE",
                "label": "auto",
                "width": 80,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/UNMUTE",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "push",
                "top": 210,
                "left": 860,
                "id": "NEXT_BAR",
                "label": "auto",
                "width": 160,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/NEXT_BAR",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "push",
                "top": 210,
                "left": 700,
                "id": "PREVIOUS_BAR",
                "label": "auto",
                "width": 160,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/PREVIOUS_BAR",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "push",
                "top": 290,
                "left": 700,
                "id": "BPM_INCR",
                "label": "auto",
                "width": 160,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/BPM_INCR",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "push",
                "top": 290,
                "left": 860,
                "id": "BPM_DECR",
                "label": "auto",
                "width": 160,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/BPM_DECR",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "push",
                "top": 350,
                "left": 700,
                "id": "BEATCOUNTER",
                "label": "auto",
                "width": 160,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/BEATCOUNTER",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "push",
                "top": 350,
                "left": 860,
                "id": "TAP_TEMPO",
                "label": "auto",
                "width": 160,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/TAP_TEMPO",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "push",
                "top": 520,
                "left": 860,
                "id": "PLAYLIST_NEXT_SONG",
                "label": "auto",
                "width": 160,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/PLAYLIST_NEXT_SONG",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "push",
                "top": 520,
                "left": 700,
                "id": "PLAYLIST_PREV_SONG",
                "label": "auto",
                "width": 160,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/PLAYLIST_PREV_SONG",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "push",
                "top": 600,
                "left": 700,
                "id": "UNDO",
                "label": "auto",
                "width": 160,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/UNDO",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "push",
                "top": 600,
                "left": 860,
                "id": "REDO",
                "label": "auto",
                "width": 160,
                "height": "auto",
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "norelease": false,
                "precision": 2,
                "address": "/Hydrogen/REDO",
                "preArgs": [],
                "target": [],
                "linkId": ""
            },
            {
                "type": "toggle",
                "top": 410,
                "left": 700,
                "id": "TOGGLE_METRONOME",
                "label": "auto",
                "width": 160,
                "height": 60,
                "color": "auto",
                "css": "",
                "on": 1,
                "off": 0,
                "value": "",
                "precision": 2,
                "address": "/Hydrogen/TOGGLE_METRONOME",
                "preArgs": [],
                "target": [],
                "linkId": ""
            }
        ]
    }
]